
[workspace]
members = [
  "ark-lib",
  "ark-testing",
  "aspd-rpc-client",
  "aspd",
  "bark",
  "bark-cln",
  "bark-json",
  "stream-until",
]

resolver = "2"

# TODO(stevenroose) at some point probably move these inline
[workspace.dependencies]

#
# * EXPORTED (ECOSYSTEM)

bitcoin = { version = "0.32", features = [ "serde", "rand", "rand-std" ] }
lightning-invoice = { version = "0.32.0-rc1", features = [ "std", "serde" ] }
lnurl-rs = "0.6.0"
# this one is a workaround for a bug in lnurl-rs
bitcoin030 = { package = "bitcoin", version = "0.30.2", features = [ "std" ] }
anyhow = { version = "1.0", features = [ "backtrace" ] }
log = "0.4.20"
serde = { version = "1", feature = [ "derive" ] }
# grpc clients
tonic = { version = "0.12.2", features = [ "tls", "tls-roots", "gzip" ] }


#
# * INTERNAL

# rust stack
lazy_static = "=1.4.0"
fern = { version = "0.6.2", features = [ "colored" ] }
hex = "=0.4.3"
clap = { version = "4.4.18", features = [ "derive" ] }
chrono = "0.4"
serde_json = "1"
ciborium = "0.2.1"
# async + gRPC stack
tonic-build = "0.12.2"
prost = "0.13.2"
tokio = { version = "1.35", features = [ "full" ] }
tokio-stream = { version = "0.1.14", features = [ "sync" ] }
futures = {version = "0.3.30"}
# bitcoin
bip39 = { version = "2.0.0", features = [ "rand", "serde" ] }
miniscript = "12.2"
rand = { version = "0.8.5", features = [ "std", "std_rng" ] }
bdk_wallet = "1.0.0-beta.5"
bdk_esplora = "0.19.0"
bdk_bitcoind_rpc = "0.16.0"
bdk_file_store = "0.17.0"


[profile.release]
debug = true
