[package]
name = "bark-client"
version = "0.0.0-alpha01"
license = "CC0-1.0"
authors = ["Steven Roose <steven@roose.io>"]
edition = "2021"
repository = "https://github.com/ark-bitcoin/bark"

[lib]
name = "bark"
path = "src/lib.rs"

[[bin]]
name = "bark"
path = "src/bin/bark/main.rs"

[dependencies]

# OWN
ark-lib = { path = "../ark-lib" }
bark-json = { path = "../bark-json" }
aspd-rpc-client = { path = "../aspd-rpc-client" }

# EXPORTED
bitcoin.workspace = true
lightning-invoice.workspace = true
lnurl-rs.workspace = true
bitcoin030.workspace = true # lnurl workaround
anyhow.workspace = true
log.workspace = true
serde.workspace = true

# INTERNAL
rusqlite =  "0.31.0"

lazy_static.workspace = true
fern.workspace = true
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
ciborium.workspace = true

bip39.workspace = true
miniscript.workspace = true
bdk_wallet = { workspace = true, features = ["rusqlite"] }
bdk_file_store.workspace = true
bdk_bitcoind_rpc.workspace = true
bdk_esplora.workspace = true

prost.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

home = "0.5.9"
