[package]
name = "bark-client"
version = "0.0.0-alpha01"
license = "CC0-1.0"
authors = ["Steven Roose <steven@roose.io>"]
edition = "2021"
repository = "https://github.com/ark-bitcoin/bark"

[lib]
name = "bark"
path = "src/lib.rs"

[[bin]]
name = "bark"
path = "src/bin/bark/main.rs"

[dependencies]
ark-lib = { path = "../ark-lib" }
bark-json = { path = "../bark-json" }
aspd-rpc-client = { path = "../aspd-rpc-client" }
sled-utils = { path = "../sled-utils" }

anyhow.workspace = true
lazy_static.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
ciborium.workspace = true
bitcoin.workspace = true
bip39.workspace = true
miniscript.workspace = true
bdk_wallet.workspace = true
bdk_file_store.workspace = true
bdk_bitcoind_rpc.workspace = true
bdk_esplora.workspace = true
lightning-invoice.workspace = true
lnurl-rs.workspace = true
bitcoin030.workspace = true
prost.workspace = true
rusqlite.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
sled.workspace = true

home = "0.5.9"
