
when:
  - event: pull_request
  - event: manual
  - event: tag
  - event: push
    branch: master

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: prechecks
    image: registry.2nd.dev/build:7
    commands:
      - just check-commits

  - name: merge-master
    depends_on: prechecks
    image: registry.2nd.dev/build:7
    commands:
      - git fetch --no-tags --depth=200 origin master
      - git log --oneline | head
      - git log --oneline origin/master | head
      - git branch prtip
      - git checkout origin/master
      - git config --global user.email "ci@codeberg.org"
      - git config --global user.name "ci"
      - git merge prtip || { git merge --abort; git checkout prtip; }
      - git log --oneline | head

  - name: build
    depends_on: merge-master
    image: registry.2nd.dev/build:7
    commands:
      - git log --oneline | head -n 1
      - cargo version
      - just build
      - ls -al ./target/debug

  - name: test-unit
    depends_on: merge-master
    image: registry.2nd.dev/build:7
    commands:
      - git log --oneline | head -n 1
      - cargo test --workspace --exclude ark-testing --target-dir ./target-unit

  - name: test-integration-btc28.0
    depends_on: build
    image: registry.2nd.dev/build:7
    environment:
      BITCOIND_EXEC: /bitcoin/28.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/24.08.2/bin/lightningd
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al $${BITCOIND_EXEC}
      - ls -al $${LIGHTNINGD_EXEC}
      - TEST_DIRECTORY=./test/btc28 cargo test --package ark-testing

  - name: test-integration-esplora
    depends_on: build
    image: registry.2nd.dev/build:7
    environment:
      BITCOIND_EXEC: /bitcoin/28.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/24.08.2/bin/lightningd
      ELECTRS_EXEC: /root/.cargo/bin/electrs
      CHAIN_SOURCE: esplora
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al ${ELECTRS_EXEC}
      - TEST_DIRECTORY=./test/esplora cargo test --package ark-testing -- --skip exit

  - name: use-bark-as-dependency
    depends_on: merge-master
    image: registry.2nd.dev/build:7
    commands:
      - git log --oneline | head -n 1
      - cargo init barktest && cd barktest
      - cargo add bark-client
      - cargo update
      - cargo build

  - name: push-github-mirror
    when:
      - event: push
        branch: master
    failure: ignore
    image: appleboy/drone-git-push@sha256:b7fbe3c66653f36d5898ccaf142be65274dc18ba260783b3a99ccc3098eed7b2
    settings:
      remote: git@github.com:ark-bitcoin/bark.git
      branch: master
      local_branch: master
      force: true
      ssh_key:
        from_secret: github-mirror-push-key

  - name: release-macos15.1-windows-linux
    when:
      - event: tag
    depends_on: test-integration-btc28.0
    image: registry.2nd.dev/build:7
    environment:
      SDKROOT: /usr/local/osxcross/SDK/MacOSX15.1.sdk
    commands:
      - just release-all
      - cd ./target
      - cp x86_64-unknown-linux-gnu/release/aspd  aspd-linux-x86_64
      - cp x86_64-unknown-linux-gnu/release/bark  bark-linux-x86_64
      - cp x86_64-pc-windows-gnu/release/bark.exe bark-windows-x86_64.exe
      - cp x86_64-apple-darwin/release/bark       bark-apple-x86_64
      - cp aarch64-apple-darwin/release/bark      bark-apple-aarch64
      - sha256sum aspd-linux-x86_64        > SHA256SUMS
      - sha256sum bark-linux-x86_64       >> SHA256SUMS
      - sha256sum bark-windows-x86_64.exe >> SHA256SUMS
      - sha256sum bark-apple-x86_64       >> SHA256SUMS
      - sha256sum bark-apple-aarch64      >> SHA256SUMS

  - name: publish
    when:
      - event: tag
    depends_on: release-macos15.1-windows-linux
    image: woodpeckerci/plugin-release@sha256:f746ad9a4e652d7b793d6aafdab3df01e7640abf66b49333ebae26edd1678c64
    settings:
      files:
        - "./target/aspd-linux-x86_64"
        - "./target/bark-linux-x86_64"
        - "./target/bark-windows-x86_64.exe"
        - "./target/bark-apple-x86_64"
        - "./target/bark-apple-aarch64"
        - "./target/SHA256SUMS"
      api_key:
        from_secret: RELEASE

