when:
  - event: pull_request
  - event: manual
  - event: tag
  - event: push
    branch: master

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: prechecks
    image: registry.2nd.dev/build:17
    commands:
      - just prechecks

  - name: check-commits
    depends_on: prechecks
    image: registry.2nd.dev/build:17
    commands:
      - just check-commits

  - name: test-unit
    depends_on: check-commits
    image: registry.2nd.dev/build:17
    commands:
      - git log --oneline | head -n 1
      - just test-unit-all-codecov

  - name: build
    depends_on: check-commits
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    commands:
      - rm -rf "/host/data/test/${CI_COMMIT_SHA}/" || true
      - rm -rf "/host/data/codecov/${CI_COMMIT_SHA}/" || true
      - git log --oneline | head -n 1
      - cargo version
      - just build-codecov

  - name: aspd-default-config-file
    depends_on: build
    image: registry.2nd.dev/build:17
    commands:
      - just default-aspd-config
      - bash contrib/check-clean-default-config.sh

  - name: use-bark-as-dependency
    depends_on: build
    image: registry.2nd.dev/build:17
    commands:
      - cargo init barktest && cd barktest
      - cargo add bark-client
      - cargo update
      - cargo build

  - name: test-integration-btc29.0
    depends_on: build
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    environment:
      BITCOIND_EXEC: /bitcoin/29.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/25.02/bin/lightningd
      TEST_DIRECTORY: ./test/btc29
      TEST_POSTGRES_HOST: localhost
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al $${BITCOIND_EXEC}
      - ls -al $${LIGHTNINGD_EXEC}
      - service postgresql start
      - just test-integration-all-codecov
      - mkdir -p "/host/data/test/${CI_COMMIT_SHA}/"
      - cp -r test/* "/host/data/test/${CI_COMMIT_SHA}/"

  - name: test-integration-esplora
    depends_on: use-bark-as-dependency
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    environment:
      BITCOIND_EXEC: /bitcoin/29.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/25.02/bin/lightningd
      ELECTRS_EXEC: /root/.cargo/bin/electrs
      CHAIN_SOURCE: esplora
      TEST_DIRECTORY: ./test/esplora
      TEST_POSTGRES_HOST: localhost
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al $${ELECTRS_EXEC}
      - service postgresql start
      - just test-integration-all
      - mkdir -p "/host/data/test/${CI_COMMIT_SHA}/"
      - cp -r test/* "/host/data/test/${CI_COMMIT_SHA}/"

  - name: code-coverage
    depends_on: [ test-integration-btc29.0, test-integration-esplora ]
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    commands:
      - just codecov-report
      - mkdir -p "/host/data/codecov/${CI_COMMIT_SHA}/"
      - cp -r target/debug/codecov/* "/host/data/codecov/${CI_COMMIT_SHA}/"

  - name: tar-and-print
    depends_on: code-coverage
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    commands:
      - tar -czf "/host/data/codecov/${CI_COMMIT_SHA}.tar.gz" "/host/data/codecov/${CI_COMMIT_SHA}/"
      - mv "/host/data/codecov/${CI_COMMIT_SHA}.tar.gz" "/host/data/codecov/${CI_COMMIT_SHA}/"
      - tar -czf "/host/data/test/${CI_COMMIT_SHA}.tar.gz" "/host/data/test/${CI_COMMIT_SHA}/"
      - mv "/host/data/test/${CI_COMMIT_SHA}.tar.gz" "/host/data/test/${CI_COMMIT_SHA}/"
      - echo "Code Coverage tar.gz -> https://ci.2nd.dev/codecov/${CI_COMMIT_SHA}/${CI_COMMIT_SHA}.tar.gz"
      - echo "Code Coverage URL    -> https://ci.2nd.dev/codecov/${CI_COMMIT_SHA}/html/index.html"
      - echo "Test data tar.gz     -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/${CI_COMMIT_SHA}.tar.gz"
      - echo "Test data URL        -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/"

depends_on:
  - main
